### ISSUE TITLE
How to obtain char embedding

### ISSUE THREAD

**Issue by zhongpeixiang** [JasonForJoy/DIM#2]
Is it one-hot embedding? or distributed embedding?

If it's distributed embedding, is it initialized from pretrained embedding or randomly? 

What's the embedding dimension? It is fixed during training?

Thanks

**Comment by JasonForJoy** [comment]
@zhongpeixiang 
Thanks for your interest in our work.
The char embedding is one-hot embedding.
Then it is processed by a CNN layer, which returns a 150-dimension embedding for each word. 
You can refer to functions of ```get_char_embedding``` and ```cnn_layer``` in the script of ```model_DIM.py``` for more details.

**Comment by zhongpeixiang** [comment]
Thank you very much for the helpful and quick response!
