### ISSUE TITLE
l2正则？

### ISSUE THREAD

**Issue by kifish** [JasonForJoy/DIM#5]
https://github.com/JasonForJoy/DIM/blob/master/model/model_DIM.py#L342，这里是不是有bug,* typo 成了 +

**Comment by JasonForJoy** [comment]
@kifish 
谢谢你的指正。

**Comment by kifish** [comment]
这里的typo其实无所谓，因为这个代码是不会触发l2 loss,即使写成*。dim有趣的一点是，不加正则(配合if valid_mrr > best_mrr)依然得到了很好的结果。
