### ISSUE TITLE
self revised persona 结果复现不了

### ISSUE THREAD

**Issue by kifish** [JasonForJoy/DIM#7]
我用了该repo的原始代码和脚本，跑self revised persona数据集，r1大概到66.5左右，达不到70.7. 是有什么地方疏漏了吗？

**Comment by JasonForJoy** [comment]
@kifish 
如果数据处理、词向量文件、vocab等都用的是我们repo下的脚本和链接，70.7的结果是完全可以复现的。
可以检查一下revised的实验设定下，train，valid和test是不是都用的是revised的数据。

**Comment by kifish** [comment]
可能是epoch数我没跑够。大概在第几个epoch可以达到70.7的结果?

**Comment by JasonForJoy** [comment]
@kifish 
和original一样，我们都将epoch最大设为10。

**Comment by kifish** [comment]
可以复现，重跑了一次。2次结果波动有点大。第二次结果比较好。
